from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class TableSchema(BaseModel):
    table_name: str = Field(description="Name of the database table.")
    columns: List[Dict[str, Any]] = Field(default_factory=list, description="Column metadata for the table.")
    primary_keys: List[str] = Field(default_factory=list, description="Primary key column names.")
    foreign_keys: List[Dict[str, Any]] = Field(default_factory=list, description="Foreign key metadata.")
    sample_rows: List[Dict[str, Any]] = Field(default_factory=list, description="Small sample of table rows.")


class DatabaseSchema(BaseModel):
    db_path: str = Field(description="Path to the SQLite database file.")
    tables: List[TableSchema] = Field(default_factory=list, description="Tables included in the database.")


class SQLPlan(BaseModel):
    question: str = Field(description="Original natural language question.")
    relevant_tables: List[str] = Field(default_factory=list, description="Tables likely needed to answer the question.")
    relevant_columns: List[str] = Field(default_factory=list, description="Columns likely needed to answer the question.")
    join_keys: List[str] = Field(default_factory=list, description="Join keys or relationships to use.")
    filters: List[str] = Field(default_factory=list, description="Filter conditions inferred from the question.")
    aggregations: List[str] = Field(default_factory=list, description="Aggregations needed for the answer.")
    order_by: List[str] = Field(default_factory=list, description="Ordering expressions needed for the answer.")
    limit: Optional[int] = Field(default=None, description="Optional maximum number of rows to return.")
    reasoning: str = Field(description="Brief reasoning behind the SQL plan.")


class GeneratedSQL(BaseModel):
    sql: str = Field(description="Generated SQLite SQL query.")
    explanation: str = Field(description="Short explanation of the generated SQL.")


class SQLExecutionResult(BaseModel):
    success: bool = Field(description="Whether SQL execution succeeded.")
    sql: str = Field(description="SQL statement that was executed.")
    columns: List[str] = Field(default_factory=list, description="Result column names.")
    rows: List[Dict[str, Any]] = Field(default_factory=list, description="Result rows as dictionaries.")
    row_count: int = Field(ge=0, description="Number of rows returned.")
    error: Optional[str] = Field(default=None, description="Execution error message, if any.")


class SQLRepairResult(BaseModel):
    repaired_sql: str = Field(description="Repaired SQL query.")
    repair_reason: str = Field(description="Reason the SQL was repaired.")


class FinalAnswer(BaseModel):
    question: str = Field(description="Original natural language question.")
    sql: str = Field(description="Final SQL used to produce the answer.")
    answer: str = Field(description="Natural language answer.")
    key_insights: List[str] = Field(default_factory=list, description="Important insights from the SQL result.")


class JudgeResult(BaseModel):
    question_sql_alignment: int = Field(ge=1, le=5, description="How well SQL matches the question.")
    answer_faithfulness: int = Field(ge=1, le=5, description="How faithful the answer is to SQL results.")
    explanation_quality: int = Field(ge=1, le=5, description="Quality of the explanation.")
    result_usefulness: int = Field(ge=1, le=5, description="Usefulness of the returned result.")
    error_analysis_quality: int = Field(ge=1, le=5, description="Quality of any error analysis.")
    has_hallucination: bool = Field(description="Whether the answer contains hallucinated content.")
    issues: List[str] = Field(default_factory=list, description="Problems identified by the judge.")
    overall_judge_score: float = Field(ge=1, le=5, description="Overall judge score.")
    judge_reason: str = Field(description="Brief reason for the judge score.")


class EvalCase(BaseModel):
    case_id: str = Field(description="Unique evaluation case identifier.")
    db_id: str = Field(description="Database identifier.")
    db_path: str = Field(description="Path to the SQLite database file.")
    question: str = Field(description="Natural language evaluation question.")
    gold_sql: str = Field(description="Reference SQL query.")
    difficulty: Optional[str] = Field(default=None, description="Optional difficulty label.")


class EvalResult(BaseModel):
    case_id: str = Field(description="Unique evaluation case identifier.")
    question: str = Field(description="Natural language evaluation question.")
    generated_sql: str = Field(description="SQL generated by the agent.")
    gold_sql: str = Field(description="Reference SQL query.")
    sql_valid: bool = Field(description="Whether generated SQL is syntactically or structurally valid.")
    execution_correct: bool = Field(description="Whether generated SQL produced the expected execution result.")
    exact_match: bool = Field(description="Whether generated SQL exactly matches the reference after normalization.")
    repaired: bool = Field(description="Whether the SQL was repaired before final execution.")
    retry_count: int = Field(ge=0, description="Number of repair or execution retries.")
    error: Optional[str] = Field(default=None, description="Evaluation error message, if any.")
    judge_result: Optional[JudgeResult] = Field(default=None, description="Optional LLM-as-a-Judge result.")


class VerificationResult(BaseModel):
    is_valid: bool = Field(description="Whether the SQL passed local verification.")
    error: Optional[str] = Field(default=None, description="Verification error message, if any.")
